#! /bin/bash

echo "TODO	: Download http://goo.gl/fd3zc"
echo "TODO	: sudo sh ~/Downloads/crouton -r trusty -t touch,xfce"
echo "TODO	: sudo enter-chroot"

sudo apt-get update
sudo apt-get install -y ssh

sudo apt-get install -y iptable
echo "ENABLE	: ssh access"
echo "EDIT	: sudo vi /etc/rc.local"
echo "TO	: enable firewall port 22"
echo "ADD	: /sbin/iptables -I INPUT -p tcp --dport 22 -j ACCEPT"
echo "TO	: Start sshd"
echo "ADD	: mkdir -p -m0755 /var/run/sshd"
echo "ADD	: /usr/sbin/sshd"

echo "ENABLE	: serial I/O for user"
sudo usermod -a -G serial $USER
sudo usermod -a -G tty $USER
sudo usermod -a -G dialout $USER

sudo apt-get install -y git
sudo apt-get install -y vim
sudo apt-get install -y tmux
sudo apt-get install -y samba
sudo apt-get install -y cmake
sudo apt-get install -y curl
sudo apt-get install -y dnsutils
sudo apt-get install -y eclipse
sudo apt-get install -y gparted
sudo apt-get install -y astyle
sudo apt-get install -y nodejs
sudo apt-get install -y valgrind
sudo apt-get install -y python-sphinx
sudo apt-get install -y usbutils
sudo apt-get install -y build-essential checkinstall
sudo apt-get install -y zip
sudo apt-get install -y maven
sudo apt-get install -y arduino arduino-core
